services:
  qwen2api:
    container_name: qwen2api
    image: rfym21/qwen2api:latest
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./data/data.json:/app/data/data.json
    environment:
      # API 路径，不填则为空(http://localhost:3000)
      # 示例(/api) 则访问 http://localhost:3000/api
      - API_PREFIX=
      # 如果需要修改Docker暴露端口，请修改ports中的参数
      # 示例(8080:3000) 则访问 http://localhost:8080
      - SERVICE_PORT=3000
      # API 密钥 (非必填)
      # 如果需要使用多账户或使用内置账户，请填写
      - API_KEY=sk-123456
      # 监听地址(非必填)
      - LISTEN_ADDRESS=
      # 搜索信息展示模式
      # table: 使用折叠块和表格展示
      # text: 使用纯文本
      - SEARCH_INFO_MODE=table
      # 是否输出思考过程
      - OUTPUT_THINK=true
      # redis 连接地址(如果使用redis模式，则必填，当redis使用tls时将redis://替换为rediss://)
      - REDIS_URL=
      # 数据保存模式
      - DATA_SAVE_MODE=none
      # 账号(如果使用redis和file模式，则不需要填写)
      - ACCOUNTS=
      # 图片缓存
      - CACHE_MODE=default
