name: Build and Run Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-run-docker:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
    
    - name: Build Qwen2API
      uses: docker/build-push-action@v4
      with:
          push: true
          context: .
          file: ./Dockerfile   # 指定 Dockerfile 路径
          tags: ricebug/qwen2api:v${{ steps.date.outputs.date }}
